### ISSUE TITLE
How to return binary data (bytes string)?

### ISSUE THREAD

**Issue by Jav3k** [RedisGears/RedisGears#499]
> Ubuntu 18.04 x86_64, Redis 6.0.10, RedisGears 1.0.5

Hello. I need to return binary data from RedisGears. But it seems to me that RedisGears converts all the data to a string

```python
import redis
import os

REDIS_HOST = os.environ.get('REDIS_HOST')
REDIS_PORT = os.environ.get('REDIS_PORT'')
REDIS_DB = int(os.environ.get('REDIS_DB', '0'))
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')

redisConn = redis.Redis(
    host=REDIS_HOST, port=REDIS_PORT, db=REDIS_DB, password=REDIS_PASSWORD, decode_responses=False
)

serverCode = '''
def generator():
  yield b'hello'

GearsBuilder('PythonReader').run(generator)
'''

res = redisConn.execute_command('RG.PYEXECUTE', serverCode)

print(type(res[0][0])) # <class 'bytes'>
```

Value of res[0][0] reply is `b"b'hello'"` (as bytes) if decode_responses=False
else `"b'hello'"` (as str) if decode_responses=True

**Comment by MeirShpilraien** [comment]
@Jav3k thanks for reporting, you are definitely right, byte array are converted to string (https://github.com/RedisGears/RedisGears/blob/94fce44e104d9414c8631dbb3a1f8c087610d793/src/redisgears_python.c#L4493). Will be fixed at the next minor version.

**Comment by MeirShpilraien** [comment]
@Jav3k I got a chance to relook at it now, seems like its ok to use `PyBytes_AsStringAndSize` it will return the underline buffer and size. The reason you get a string is because, by default, all the records are mapped to strings. You can turn this off with `convertToStr=False` parameter to the run `function` (https://oss.redislabs.com/redisgears/functions.html#run)
```
def generator():
  yield b'\x01\x11'

GearsBuilder('PythonReader').run(generator, convertToStr=False)
```
If I run this in gears-cli I get this result:
```
> gears-cli run test.py 
Results
-------
1)	
```
While if I run it with `convertToStr=True` I get this result:
```
> gears-cli run test.py 
Results
-------
1)	b'\x01\x11'

```

**Comment by MeirShpilraien** [comment]
@Jav3k can we close this one?
