### ISSUE TITLE
Changed behavior of `RG.CONFIGGET` in 1.2.0

### ISSUE THREAD

**Issue by d00astro** [RedisGears/RedisGears#554]
**Describe the bug**
In version 1.2.0 and 1.2.1 `RG.CONFIGGET` behaves differently from 1.0.X:
   A. It does not accept custom config names, See steps 3 and 4 below
   B. It is case sensitive, See steps 5, 6 and 7

It seems like `RG.CONFIGSET` still works as before.

**To Reproduce**
1. `docker run --rm --name gears -d -p 6379:6379 redislabs/redisgears:1.2.0`
(also 1.2.1)

2. `redis-cli`

3. Store a custom config (seems ok):
```
RG.CONFIGSET ThisIsACustomConfig 42
1) OK - value was saved in extra config dictionary
```

4. Try to get it back (A):
```
RG.CONFIGGET ThisIsACustomConfig
1) (error) (error) Unsupported config parameter: ThisIsACustomConfig
```

5.Setting a config with any case (ok):
```
RG.CONFIGSET maxexecutions 1337
1) OK
```

6. Getting a config in camel-case (ok):
```
RG.CONFIGGET MaxExecutions
1) (integer) 1337
```

7. But seems to be case sesnsitive (B):
```
RG.CONFIGGET maxexecutions
1) (error) (error) Unsupported config parameter: maxexecutions
```

**Expected behavior**
Step 4 should return what was set in step 3 (i.e. 42)
Step 7 should return same as step 6 (i.e. 1337)

**Environment (please complete the following information):**
 - OS: host: Ubuntu 20.04, container: Debian Buster
 - Version: Redis: 6.0.9, RedisGears: 1.2.0 and 1.2.1
 - Platfrom: x86

**Comment by MeirShpilraien** [comment]
Thanks @d00astro, will check it out.

**Comment by MeirShpilraien** [comment]
@d00astro checked it out and you are totally correct. This PR should fix the issue: https://github.com/RedisGears/RedisGears/pull/557

Regarding case insensitive, I agree that on v1.0.x you can add a case insensitive config but only the RedisGears config values, the user define config values are not case insensitive:
```
127.0.0.1:6379> RG.CONFIGSET test test
1) OK - value was saved in extra config dictionary
127.0.0.1:6379> RG.CONFIGGET test 
1) "test"
127.0.0.1:6379> RG.CONFIGGET Test 
1) (error) (error) Unsupported config parameter: Test
```

So because we never documented (at least from what I know) that config names are case insensitive I believe we can break it to match the behavior.
